#!/usr/bin/bash
# Assigns start and endpoint range for CDR3s in Heavy Chain Sequences according to Kabat and Chothia rules for antibody numbering
# Identifies outliers that were not detected by heavychainCDR3finder1 by redefining range in between Cys-Ala-Arg and Trp-Gly
    for file in /HCALL/*;
    do
    perl -l -ne 'print $1 if /W(....................................................................................................................................)/sg' *.faa > cutCDR3two.faa
    done
    perl -l -ne 'print $1 if /CAR(.*?)WG/sg' cutCDR3two.faa > cutCDR3againtwo.faa
    grep -Po '^.{2}\K.*' cutCDR3againtwo.faa > CDR3stwo.faa

    
