#!/usr/bin/bash
# Assigns start and endpoint range for CDR2s in Heavy Chain Sequences according to Kabat and Chothia rules for antibody numbering
# to find CDR2s in Heavy Chain Sequences. 
#Since there is greater variance, Gives APPROXIMATE region based on average of AbM And Chothia minimum and maximum lengths. 

    perl -l -ne 'print $1 if /W(........................................)/sg' *.faa > cutthesecdrs2.faa
    
    grep -Po '^.{14}\K.*' cutthesecdrs2.faa > cutthesecdrsagain2.faa
# always 15 after end of Kabat/AbM definition

    sed -e 's/^\(.\{12\}\).*/\1/' cutthesecdrsagain2.faa > CDR2s.faa
# Cutting off 7 residues earlier, according to AbM and Chothia, but taking Kabat 16 to 19 residues and subtracting 7 from each and taking average.
