#!/usr/bin/bash
# Assigns start and endpoint range for CDR3s in Light Chain Sequences, and trims the final 7-11 characters to obtain the CDR3 between C always and between first FG occurence
# According to kabat and Chothia antibody numbering rules.
# Note that for any outliers obtained, 
# perl -ne 'print unless length > 3;' CDR3s.faa, gives me QQ and CS, Download GNU Parallel before next step.
# do find . -type f | parallel -k -j150% -n 1000 -m grep --color=always -H -n STRING {} , string can be CQQG, CCSG etc. Between Cys and Gly
# look before 7-11 residues and after 7-11 residues on the matched faa files and find manually. CS correct, QQ is next set of FGs. in other words 97-98% accurate

  for file in /LCALL/*; 
    do
    perl -l -ne 'print $1 if /W(..................................................................)/sg' *.faa > cutthesestringsforcdr3.faa
    done

    grep -o '.............................................$' cutthesestringsforcdr3.faa > cutonemoretimeforcdr3.faa
    perl -l -ne 'print $1 if /C(.*?)FG/sg' cutonemoretimeforcdr3.faa > CDR3s.faa
