#!/usr/bin/bash
# Updated Sep 12 2022
# Assigns start and endpoint range for CDR3s in Light Chain Sequences, and trims the final 7-11 characters to obtain the CDR3 between C always and between first FG occurence
# According to kabat and Chothia antibody numbering rules.
# Note that I obtained outliers in my data, which are sequence strings less than 7 residues, let this be x. This can be checked with following Perl command;
# perl -ne 'print unless length > 3;' CDR3s.faa. Download GNU Parallel before next step.
# do find . -type f | parallel -k -j150% -n 1000 -m grep --color=always -H -n STRING {} , STRING can be CQQG, CCSG etc. Sequence string x is between Cys and Gly.
# Look 7-11 residues before and after the highlighted grep text on the matched .faa files and find the sequence manually.

  for file in /LCALL/*; 
    do
    perl -l -ne 'print $1 if /W(..................................................................)/sg' *.faa > cutthesestringsforcdr3.faa
    done

    grep -o '.............................................$' cutthesestringsforcdr3.faa > cutonemoretimeforcdr3.faa
    perl -l -ne 'print $1 if /C(.*?)FG/sg' cutonemoretimeforcdr3.faa > CDR3s.faa
