#!/bin/bash
# Finds Complementary determining region 1 in Light Chain Sequences according to Kabat and Chothia rules for antibody numbering.
# Finds sequence starting after first Cys and ending before first TRP, length approximately 10-17 residues
# -0 counts as an interpreter to interpret numbers from 0-7 (octal) and 3 following octal digits after the 0. Normally used in line scripts, adding -0(000) is for paragraph modes.
# -l outputs on newline,
# -n reads the input line by line, 
# -e indicates the code itself follows after e,
# $ matches end of string.
# /C/ for first C detected in the range,
# .*? is a non-greedy regular expression to end the sequence before the first W. 
# Without the ?, the .* acts as a flag to include all characters before last W.
# s changes dot metacharacter so it matches ANY character at all.
# g is for GLOBAL matches that match ALL occurences of the pattern within the string.
# check output then do ./CDR1finder > combined.faa to combine all fastas together again with the CDR sequence 
# After strings are printed, type ./lightchainCDR1finder > CDR1s.faa to output the Complementary Determining Region 1s into a FASTA file.
  for file in /LCALL/*; 
    do
    perl -l -ne 'print $1 if /C(.*?)W/sg' *.faa
  done

 
