#!/bin/bash
#this reruns from MassRecalibration. Updated Sep 12 2022

mono MaxQuant/bin/MaxQuantCmd.exe mqpar.xml
result=1
while [ $result -ne 0 ]; do
    mono MaxQuant/bin/MaxQuantCmd.exe mqpar.xml --partial-processing=14
    result=$?
done
