#!/bin/bash
# Used in accompaniment with S1finder. Updated Sep 12 2022
# Finds RBD regions between 319-541 residues as given in https://www.nature.com/articles/s41401-020-0485-4, given an input of spikeglycoproteins as FASTAs. 


 grep -Po '^.{318}\K.*' Spikeproteins.faa > cuttheseagain.faa
# cuts from behind to start at the defined RBD range

 sed -e 's/^\(.\{223\}\).*/\1/' cuttheseagain.faa > RBDs.faa
# cuts from front to end at character 541 in the defined RBD range. 


